import VerifyClient from './VerifyClient';

export const metadata = {
  title: 'Verify Certificate — Prompt Engineering',
  description: 'Verify a Prompt Engineering certificate of completion.',
  /* NOT IN THE ORIGINAL noindex LIST — added for a privacy reason, see the
     commit message.

     This page renders the certificate holder's name. The URL is generated by
     the certificate page's "copy link" button, so it is meant to be shared and
     is therefore discoverable from wherever it is pasted. Without this tag it
     was indexable, which would put 33 real people's names into search results
     as a side effect of finishing a free course.

     Crawlable and noindex, not disallowed: anyone given the link must still be
     able to verify a certificate, and a Disallow would leave any already
     indexed page stuck there permanently. */
  robots: { index: false, follow: false },
};

export default function VerifyPage({ params }) {
  return <VerifyClient certId={params.certId} />;
}
